### ISSUE TITLE
Change (format) to (printf)

### ISSUE THREAD

**Issue by shymega** [vktec-irc/warnserv#1]
According to @vktec, (printf) is more idiomatic in CHICKEN Scheme, than (format). [citation needed]

(Read: ```refactor``` branch.)

**Comment by shymega** [comment]
OTOH, I kinda prefer (format). @vktec - do you have a source for (printf) being more idiomatic? Thanks.

**Comment by vktec** [comment]
[`(format)`][1] is simply a wrapper that calls `(printf)`, `(sprintf)`, or `(fprintf)` depending on it's arguments.

This means that the code

```scheme
(format #t "~A costs \u00A3~A~%" "1 apple" 1.59)
```

is equivalent to 

```scheme
(printf "~A costs \u00A3~A~%" "1 apple" 1.59)
```

Personally, I see no reason _not_ to use `(printf)`, especially as `(format)` calls it anyway.

[1]: http://api.call-cc.org/doc/extras/format

**Comment by vktec** [comment]
Fun fact: neither `(format)` _nor_ `(printf)` exist as part of the R5RS specification, which means that the CHICKEN developers are _only_ including `(format)` to be compatible with Common Lisp.

**Comment by shymega** [comment]
Yep, thanks @vktec.

I'm sure that I'm inclined to use (format) because of my previous experience with Common LISP. 

I am going to fix this issue later by replacing (format) with (printf). Hopefully it should be compatible, especially if it's just a wrapper.

**Comment by vktec** [comment]
`sed 's/(format #t/(printf/g' -i file-to-change` should do the trick

**Comment by shymega** [comment]
Samadi van Koten <notifications@github.com> writes:

> `sed 's/(format #t/(printf/g' -i file-to-change` should do the trick

Yeah, I was gonna use a regex to change this.

Will fix soon, thanks.

-- 
Best regards,
Dom Rodriguez

**Comment by shymega** [comment]
This issue has been fixed in the ```refactor``` branch.

For now, this issue will stay open until ```refactor``` is ready to be merged into master.

**Comment by shymega** [comment]
This is fixed in the `refactor` branch.

Closing issue, as this is resolved.
